### ISSUE TITLE
Use Sketch.js

### ISSUE THREAD

**Issue by regnerus** [PRINTR3D/javascript-3d-doodler#5]
I came across this library called Sketch.js (http://soulwire.github.io/sketch.js/) Its small, supports things like multitouch etc and integrates well with Three.js

Could you look into this? Maybe their integration with three.js can do the transformation to 3d without creating the “holes/missing planes”etc.

**Comment by FlorisVeldhuizen** [comment]
I looked at the examples, and it seems that sketch.js is not really oriented towards actually sketching, it can be seen as a "processing"- or "open frameworks"-like wrapper for javascript to develop in. 

Since my app is designed with different functions that depend on images rather than touch locations, this is not really compatible unless I rewrite everything... Thanks for the suggestion though ;)
